version: '3.9'

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    restart: 'unless-stopped'
    networks:
      - backend

  api-server:
    image: ${{ secrets.DOCKER_USERNAME }}/phayu:latest
    ports:
      - '8888:8888'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
