version: '3.9'

services:
  app:
    image: phayu:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    environment:
      DATABASE_URL: mysql://root:tiktrack@mysql:3306/phayu
    networks:
      - network-connect
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=tiktrack
      - MYSQL_USER=tiktrack
      - MYSQL_PASSWORD=tiktrack2024
    volumes:
      - ./mysql:/var/lib/mysq
    networks:
      - network-connect

  redis:
    container_name: redis_hono
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
    networks:
      - network-connect

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - network-connect

volumes:
  jenkins_home:

networks:
  network-connect:
    driver: bridge
